# Generated by Django 2.1.2 on 2018-11-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
